ignoredBuiltDependencies:
  - bufferutil

packages:
  - "packages/chrome"
  - "packages/cdp"
  - "packages/devtools"
  - "packages/sandbox"
  - "packages/inject"
  - "external/dreamlandjs"
  - "packages/scramjet"
  - "packages/scramjet/packages/core"
  - "packages/scramjet/packages/bootstrap"
  - "packages/scramjet/packages/controller"
  - "packages/scramjet/packages/scramjetserver"
  - "packages/scramjet/packages/bare-mux-custom"
  - "packages/scramjet/packages/epoxy-transport"
  - "packages/scramjet/packages/libcurl-transport"
  - "packages/scramjet/packages/demo"
  - "packages/scramjet/packages/rewriter_demo"
  - "packages/scramjet/packages/rpc"
  - "packages/scramjet/packages/typedoc"
  - "packages/scramjet/packages/create-proxy-app"
